### ISSUE TITLE
缺少主题配置文件_config.yml

### ISSUE THREAD

**Issue by leeifme** [Vincentqyw/blog-code#4]
无意间看见你修改的博客主题，很喜欢。
clone后运行，发现少了`_config.yml` ，用原版的配置文件，发现字体和很多样式都没正确显示。
所以想麻烦更新下，Thanks.

**Comment by Vincentqyw** [comment]
你好，当时我是故意删掉的，因为里面有好多暴露的ID。你留个邮箱我发给你吧，过段时间我也会再更新下。

**Comment by Vincentqyw** [comment]
@leeifme 你好，当时我是故意删掉的，因为里面有好多暴露的ID。你留个邮箱我发给你吧，过段时间我也会再更新下。

**Comment by leeifme** [comment]
好的 谢谢！
邮箱是 lee@leeif.me

**Comment by Vincentqyw** [comment]
@leeifme 已回复邮件。
